/**
 *	VIP registers for deca_graphics demo
 */
enum MIXER_REGISTER
{
    MIXER_REGISTER_CONTROL = 0,
    MIXER_REGISTER_STATUS,
    MIXER_REGISTER_LAYER0_X = 3,
    MIXER_REGISTER_LAYER0_Y,
    MIXER_REGISTER_LAYER0_ENABLE,
    MIXER_REGISTER_LAYER1_X = 8,
    MIXER_REGISTER_LAYER1_Y,
    MIXER_REGISTER_LAYER1_ENABLE,
    MIXER_REGISTER_LAYER2_X = 13,
    MIXER_REGISTER_LAYER2_Y,
    MIXER_REGISTER_LAYER2_ENABLE,
    MIXER_REGISTER_LAYER3_X = 18,
    MIXER_REGISTER_LAYER3_Y,
    MIXER_REGISTER_LAYER3_ENABLE,
};

enum FRAMEREADER_REGISTER
{
    FRAMEREADER_REGISTER_CONTROL = 0,
    FRAMEREADER_REGISTER_STATUS,
    FRAMEREADER_REGISTER_FRAME_SELECT = 3,
    FRAMEREADER_REGISTER_FRAME0_BASE,
    FRAMEREADER_REGISTER_FRAME0_WORDS,
    FRAMEREADER_REGISTER_FRAME0_SCCP,
    FRAMEREADER_REGISTER_FRAME0_WIDTH = 8,
    FRAMEREADER_REGISTER_FRAME0_HEIGHT,
    FRAMEREADER_REGISTER_FRAME0_INTERLACED,
    FRAMEREADER_REGISTER_FRAME1_BASE,
    FRAMEREADER_REGISTER_FRAME1_WORDS,
    FRAMEREADER_REGISTER_FRAME1_SCCP,
    FRAMEREADER_REGISTER_FRAME1_WIDTH = 15,
    FRAMEREADER_REGISTER_FRAME1_HEIGHT,
    FRAMEREADER_REGISTER_FRAME1_INTERLACED,
};

enum TPG_REGISTER
{
    TPG_REGISTER_CONTROL = 0,
    TPG_REGISTER_STATUS,
    TPG_REGISTER_WIDTH = 3,
    TPG_REGISTER_HEIGHT,
};